name: CI/CD Pipeline for Customer Churn Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set Up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Unit Tests
      - name: Run Unit Tests with Pytest
        run: pytest tests/

      # Step 5: Train the Model and Log with MLflow
      - name: Train the Model
        run: python src/train_model.py

      # Step 6: Trigger Databricks Job for Model Deployment
      - name: Trigger Databricks Job
        run: |
          databricks jobs run-now --job-id ${{ secrets.DATABRICKS_JOB_ID }}
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      # Step 7: Notify on CI/CD Completion
      - name: Notify Success
        run: echo "CI/CD Pipeline completed successfully!"
